apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAdRbueTyvzoWxIeFA6PHmPQwAS3kHAfG7V+IZYXWGAivr4Dzh+R61sGzXjuKbFVjXBmimSsTBgoYq3PyOaeRZ1ijPDlKMOADBtGu7LLQuKMw2/x4u70Q9JJz3D7iot+WCMdh8pUX3kpBVxa2diY3IDVQyboO0nV9LevD0Dr4gn7oxIk1PCfSDSyTamVrm5SyWtERq0+idCyoIirczMjWYvOVyIWzvzuQNI1jfNKNtTS8zJB/iUjCa0OWqII79reZFvocpqBUunNMhCipq0DiQH1AsRyr8Z0mqQ7rb0eOKZmzv4pPjvF1L+AW6156ctexc6t3uQZoaVyQQI8zC7MAvRkASA6MN50bRoyO1UrmRZ1ky1dfVMhqY0vfVbY4aUT63rnFQJg2zIFqZuk7fFoPnJtLsunCRfFr7DWuW9fZsrwwIhPTdP480teY411VAwZs9hHs964HtWXQ4XpBzYZnq5Djj9AkqUf+dFc2GLOCpFc4x+48dDI3RfaPVv1hHhTveha6hLvNZk+YXTZN31ttpsLrb3IAB31yDGYw6livd9dzpj1D7cxRv2sEIimiodQe2leUhIjFe2g1o+SA9IVp0Dcr47jPlMijm47WUibNQaM7gk58Qna5qVtto2D3IaKsm0sr2LiVlJ565x6FMPPwXmb1v8RLDuP+8xmQLl/ZY4qMLBNi3u9fg65JhYqIr21EgMabbXa6mZ2w==
    DB_USER: AgAIweL5/GGBDweHVjlDtjuoLi17vLQCpJtwZuyIrb7kXuWXzAX+mzmhQN1ZP3+Qd9SlLIK3bhzU4xcfxC5CasJ/WGaZ1bhjEWy4Cqtpwj9A4HvIBosweRmYHCo47/FhfQV61NUrfXOsIkm0dL3obtWjWY9dnOgRekgtu1lNCHx5c3BN7JQiH0tusjpIQg5+T9a5xA15f+Vpdet/vJMKu9GeVH8T72KVPG2j/kMzYGrPxjefTBj+TiPC/SPemivs0/M5rwUcrQGvKvO07i9/+8Fb2KBGrNzSvJ2vZ4qqeYRxn78Ve6KQKtahZlrawPxX1h+3ZiCBAsSCWXmEDg9biVJETSwmgLHZUlvtKOwGu7ycbIGnRazpPzF6kWMTxFBMMivvmqgs9zzSW/x3PE5w9m5heOzEV8qSbrT1ZnfaX+xrbZMTGvOGhx50lhxhdX34UuaaK0REDDVVHnl2RGu9gQSC+sO3TERp+0gOxaoargK8TsifFs8kOynLBaxUP7d+hzAxt78aKl/h4ZO2l6w6SZMo3y5PPRFrfeSH8esldmHVhl2ehIpH1ieMO6b36s9+Qhtd3TJOD+oDfplHLt3hshWPQobHnP1WC8yZ0I3EDeQ9G6Iz7Ck+Sv1MKpwGrBh2VCCje/1qif9DX8x+VF1OVAromyZKDuwh4o3PG+RSd6T8d+3Bgnp1ZiB1goRuWoFVao1Z/0sbdGjTig==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

